### PR TITLE
feat: ui fixing, flip animation

### PR DESCRIPTION
**Pull request by LordRonz**
### Detailed description of changes
- added peel animation component https://www.youtube.com/watch?v=eV9ybRJpuB8
- modify maze texture

### Screenshots or videos (before and after if appropriate)
Simulator Screen Recording - iPad Pro (12 9-inch) (6th generation) - 2023-10-29 at 00 44 42

### Checklist for developer
- [x] The code builds clean successfully
- [x] The code does not log anything to console
- [x] I have thoroughly tested the new code and any adjacent features it may affect

### CODE REVIEW

**Comment by LordRonz** [comment]
@carissafarry kemarin storybooknya yg kamu tambahin background dimana ya

**Comment by carissafarry** [comment]
@LordRonz belum tak up. Tadi ilang btw, ga ilang si. Project nya rusak, ga bisa dibuka di xcode wkw

**Review by carissafarry — APPROVED** [review]

**Comment by LordRonz** [comment]
> @LordRonz belum tak up. Tadi ilang btw, ga ilang si. Project nya rusak, ga bisa dibuka di xcode wkw

owh yasudah 😂

**Review by carissafarry — APPROVED** [review]

**Review by carissafarry — APPROVED** [review]

**Comment by LordRonz** [comment]
ini udah include popup yang gajelas muncul2nya, dan animasinya udah better

**Pull request merged**
