### PR TITLE
Feat/maze view

### PR DESCRIPTION
**Pull request by LordRonz**
https://macro-team-8.atlassian.net/browse/MC-79?atlOrigin=eyJpIjoiYWU1NDY4MWFlZGU0NDBmNTk3MjE1YTc4MjBmZjA0YzEiLCJwIjoiaiJ9

### CODE REVIEW

**Comment by LordRonz** [comment]
gajelas ni ios workflow kadang work kadang ga

**Review by carissafarry — APPROVED** [review]

**Review by Nielioo — COMMENTED** [review]
~~:|:~~

**Comment by Nielioo** [comment]
> gajelas ni ios workflow kadang work kadang ga

Gitu kenapa ron?

**Review by Nielioo — APPROVED** [review]

**Comment by LordRonz** [comment]
> > gajelas ni ios workflow kadang work kadang ga
> 
> Gitu kenapa ron?

gatau juga wkwk

**Pull request merged**
